Vagrant.configure("2") do |config|

  config.vm.define "dns1" do |dns1|
    dns1.vm.box="ubuntu/focal64"
    dns1.vm.network "private_network", type: "dhcp"
    dns1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "dns2" do |dns2|
    dns2.vm.box="ubuntu/focal64"
    dns2.vm.network "private_network", type: "dhcp"
    dns2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "web" do |web|
    web.vm.box="centos/7"
    web.vm.network "private_network", type: "dhcp"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
